[package]
name = "bevy_crossterm"
version = "0.1.0"
authors = ["AlephAlpha <alephalpha911@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.4.0"
bevy_input = "0.4.0"
crossterm = "0.18.2"
